name: "📝 New Snip"
description: "Add a new snip to your brain"
title: "[SNIP] "
labels: ["snip"]
body:
  - type: input
    id: title
    attributes:
      label: "Snip Title"
      description: "What's this snip about?"
      placeholder: "Enter a descriptive title..."
    validations:
      required: true
  
  - type: textarea
    id: content
    attributes:
      label: "Content"
      description: "Your snip content (markdown supported)"
      placeholder: |
        Enter your snip content here...
        
        You can use markdown formatting:
        - **bold text**
        - *italic text*
        - `code snippets`
        - [links](https://example.com)
    validations:
      required: true

  - type: input
    id: source
    attributes:
      label: "Source (optional)"
      description: "Where did this come from?"
      placeholder: "Book, article, conversation, etc."

  - type: input
    id: tags
    attributes:
      label: "Tags (optional)"
      description: "Comma-separated tags"
      placeholder: "productivity, ideas, quotes" 